purebred-mua/purebred-email

src/Data/RFC5322.hs
isAtext was mistakenly specifying a range from ASCII characters '+' to '/' which
included ASCII characters like ',', '-' and '.'. This resulted in wrong parser
results, even tho not very obvious.
This patch puts the dash to the beginning in accordance to the documentation.
=> Specify dash for isAtext at the beginning

purebred-email.cabal, src/Data/RFC5322.hs, src/Data/RFC5322/Address/Text.hs, src/Data/RFC5322/Address/Types.hs, tests/Headers.hs
There is a need in purebred to also be able to parse addresses which are Text.
Instead of using the ByteString parser, this patch adds an additional parser for
parsing Addresses using Text values.
=> Text based Address parser

src/Data/MIME.hs, tests/Headers.hs
RFC5322 - 3.6.4 specifies identification fields used when the user replies to a
message. This patch adds a getter which might return a ByteString in the effect
the rules defined in 3.6.4 return the necessary header values from the original
message. The ByteString can be used to set the 'references' field value in the
replied message header.
=> Provide an optic to retrieve a value setting the 'References' field

.travis.yml, src/Data/MIME.hs, test-vectors/nested-multipart.eml, tests/MIME.hs
RFC 2046 defines:
multipart-body := [preamble CRLF]
dash-boundary transport-padding CRLF
body-part *encapsulation
close-delimiter transport-padding
[CRLF epilogue]
Our current MIME parser is defined as (equivalent to):
...
closeDelimeter <* crlf <* takeTillEnd
where 'takeTillEnd' provides everything up to the "end" of the
message, which for a "top-level" multipart message is the end of the
entire input, and for a nested multipart message is everything up
to, but not including, the boundary of the enclosing multipart
message, __preceded by a LF__.
Therefore a mail containing nested multipart messages where the
close-delimeters are separated by only a single newline does not
parse.  For example, the following message will not parse:
```
Content-Type: multipart/mixed; boundary=boundary1 …
```
=> fix MIME epilogue parsing

src/Data/RFC5322/Internal.hs, tests/Headers.hs
From RFC 5322, Section 3.2.2:
> Runs of FWS, comment, or CFWS that occur between lexical tokens in a
> structured header field are semantically interpreted as a single
> space character.
When folding words into a phrase, we have to re-insert these single
spaces.
Example: In the address `John Doe <jdoe@example.com>`, the display name
should parse as `John Doe` instead of `JohnDoe`.
Fixes #27
=> Keep `word`s in a `phrase` separated by whitespace.

src/Data/RFC5322/Address/Text.hs, tests/Headers.hs
This is a needed for round tripping mails in purebred: when editing
mails as new, we want to populate the editor fields with header
values. Using a combination of header* lenses with rendering the given
addresses populates the fields without re-implementing those functions
on the purebred side.
=> Expose functions to render addresses to text

src/Data/RFC5322/Address/Text.hs
These parsers will be valuable add-ons to use when roundtripping mails
in purebred.
=> Export parsers for parsing address and mailbox lists

tests/Headers.hs
This was mistakenly changed to appease hlint in
28428a91eef9a5a0a0b608c61ea820dc96d5b024 but actually broke the test.
=> Revert change for generator

src/Data/MIME.hs, src/Data/RFC5322.hs, src/Data/RFC5322/Address/Text.hs, src/Data/RFC5322/Internal.hs, tests/Headers.hs
```
f454f4c (Fraser Tweedale, 25 seconds ago)
doc: show how to set To/From/Cc/Bcc
4758379 (Fraser Tweedale, 15 minutes ago)
add tests for headerFrom/To/CC/BCC
f366d8c (Fraser Tweedale, 24 minutes ago)
fix dot-atom parsing
We were parsing dot-atoms into a (NonEmpty ByteString), but always as a
singleton that included the whole name *with dots*.  Names were not broken
up into fragments as they should be.
Fix the parsing and update tests accordingly.
47d597c (Fraser Tweedale, 4 hours ago)
fix From/To/Cc/Bcc header optics
The headerFrom, headerTo, headerCC and headerBCC optics cannot be used to
set the header if the header was not already present
(because 'header k' is a Traversal).  Refactor these optics to use
'at k' instead along with an Iso for converting between the 'Maybe 
ByteString' …
```
=> fix headerFrom/To/CC/BCC, add doc; fix dot-atom parsing

src/Data/MIME.hs, src/Data/RFC5322.hs, tests/Generator.hs, tests/Parser.hs, tests/golden/multipart.golden
```
e8488e0 (Fraser Tweedale, 5 minutes ago)
support parsing messages with no body
RFC 5322 and its predecessors define message as:
message         =   (fields / obs-fields)
[CRLF body]
The body is optional, and there is syntactic and semantic difference 
between an empty body and a missing body.  Enhance purebred-email to 
support parsing message types that do not have a body, or have an optional
body.
Also add a default implementation for EqMessage:
default eqMessage :: (Eq a) => Message s a -> Message s a -> Bool
Fixes: https://github.com/purebred-mua/purebred-email/issues/35
89c0c3a (Fraser Tweedale, 2 hours ago)
generalise buildMessage and renderMessage
buildMessage and renderMessage were specialised to MIME payloads. But to
support other payload types using RFC 5322, generalise …
```
=> support message types with no body or optional body

src/Data/MIME.hs, src/Data/RFC5322.hs, tests/MIME.hs
Fixes #46 so that Date header can be added when not already present (with test).
Fixes #16 so that invalid Date header results in Nothing and not bottom (with test).
Allow a slightly more lax version of dates for parsing.
=> headerDate when header not present, and parsing invalid header

src/Data/MIME.hs
Matches other headers (To, From, etc) even though it shouldn't change
function the first-letter-caps is traditional.
=> Use capital D for Date header

src/Data/MIME/QuotedPrintable.hs
```
a419c34 (Fraser Tweedale, 15 minutes ago)
do not wrap lines in Q encoding
Q encoding has a maximum length, but the way that Quoted-Printable encoding
wraps lines is incorrect for Q encoding.  So punt on this problem: raise
the wrap limit for Q encoding to (maxBound :: Int), to effectively prevent
wrapping.
03614b9 (Fraser Tweedale, 20 minutes ago)
encode '?' in Q encoding
Q transfer encoding requires '?' (63, 0x3f) to be encoded, but this was not
being done.  Make it so.
6e1890e (Fraser Tweedale, 20 minutes ago)
encode '\t' in Q encoding
Q transfer encoding requires HTAB ('\t'; 0x09) to be encoded, but this was
not being done.  Make it so.
```
=> Q encoding fixes

src/Data/RFC5322.hs, tests/Headers.hs
The header wrapping will wrap a long word to the next line, even if
it is the first word. This is legal, but a bit awkward and
unnecessary.  It also complicates header processing e.g. when the
initial datum is an encoded-word value, the interpretation includes
spurious leading whitespace.
Filter out empty folded lines to avoid this problem.
=> header folding: filter out empty lines

src/Data/MIME/Base64.hs
'joinWith' was removed in base64-bytestring v1.1.  Implement this
behaviour another way.
Related: https://github.com/purebred-mua/purebred/issues/388
=> avoid base64-bytestring 'joinWith' function

src/Data/RFC5322.hs, tests/Message.hs
Amusingly, when I wrote the current implementation I foreshadowed
this bug:
```
-- FIXME: this probably doesn't handle consecutive SPACE properly
-- due to FWS:
--
--    quoted-string   =   [CFWS]
--                        DQUOTE *([FWS] qcontent) [FWS] DQUOTE
--                        [CFWS]
--
-- Do not be surprised if the roundtrip property fails
```
To fix it, escape space chars (all of them) in the quoted-string if
any consecutive space chars appeared.
Fixes: https://github.com/purebred-mua/purebred-email/issues/56
=> fix encoding of phrases with consecutive space chars

.github/workflows/haskell-ci.yml, purebred-email.cabal, src/Data/MIME.hs, src/Data/RFC5322.hs, src/Data/RFC5322/Address/Text.hs, src/Data/RFC5322/Address/Text.hs-boot, src/Data/RFC5322/Address/Types.hs, src/Data/RFC5322/Address/Types.hs-boot, src/Data/RFC5322/DateTime.hs, src/Data/RFC5322/Internal.hs, tests/Generator.hs, tests/Headers.hs, tests/MIME.hs, tests/Message.hs, tests/Parser.hs
Highlights:
- A new `reply` function, for constructing replies.  Behaviour is
configurable via the `ReplySettings` type.  This supports the
reply and reply-all/group-reply functions in purebred, but replying
is a general concept, the rules/guidelines for construction are written
in RFC 5322, and so this behaviour belongs here in *purebred-email*.
- Proper `MessageID` type; parsing, serialisation and optics for `Message-ID`,
`In-Reply-To` and `References` headers.
- More correct handling of Date header (#49)
- Implement RFC 6854 changes to `From` and `Sender` header syntax (#53)
- Add `instance IsString Mailbox` (#18)
- Compare domain names in addresses case-insensitively.
```
Changes:
26b2090 (Fraser Tweedale, 2 hours ago)
ci: test with GHC 8.8 .. 9.0
GHC < 8.8 has too-old version of …
```
=> many wonderful changes (v0.5)

purebred-email.cabal, src/Data/IMF.hs, src/Data/MIME.hs, src/Data/MIME/Boundary.hs, tests/Generator.hs, tests/MIME.hs, tests/Message.hs
This is quite a meaty pull request but the main things are:
- implement restrictions on boundary parameter as required by RFC
- implement random generator for boundary parameter
- remove deprecated `ctEq` function
- make content-type part of the structural representation of multipart and
encapsulated messages.  This avoids accidental manipulation of the
content-type that causes the header to no longer match the data structure.
This is not yet bullet-proof - you can still manipulate the header, but the
modified value will be ignored when serialising multipart or encapsulated
messages.  It is a step in a good direction.
```
c7a0607 (Fraser Tweedale, 14 minutes ago)
remove deprecated function ctEq
ctEq has been deprecated since v0.1.0.0, the first public release of 
purebred-email.  Time to …
```
=> implement boundary restrictions, other enhancements

src/Data/IMF.hs, src/Data/IMF/Syntax.hs
Partial support for RFC 6532.  For now, only unstructured headers
(e.g. Subject) allow UTF-8.
Fixes: https://github.com/purebred-mua/purebred-email/issues/82
=> support utf-8 in unstructured headers

CHANGELOG.md, src/Data/MIME.hs, test-vectors/multipart-no-body.eml, tests/MIME.hs, tests/Message.hs
Add support for parsing and constructing MIME parts without bodies. The new `entities'` traversal visits all parts, projecting `Just body` where there is a body, and `Nothing` where there is no body. The `MIME` data type gets the new `PartNoBody` constructor.
This was a rather intrusive change.  Instead of passing around the parser for "take a part at the current level", we pass around a new data type that represents the current level:
data MIMELevel = Top | Nest B.ByteString {- delimiter -}
We construct the "take part" parser on-demand where needed, and when we are parsing terminal parts in a multipart message we avoid preceding the delimiter with CRLF.  This lets us detect and handle the "no body" case.
Fixes: https://github.com/purebred-mua/purebred-email/issues/90
=> support MIME subparts without bodies
